name: build

on:
  # push:
  #   branches:
  #     - main
  #     - 'release/**'
  workflow_dispatch:

permissions:
  contents: write  # Need write permission to commit back to repo
  pull-requests: read  # Need to read PR information

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for git log

      - name: Generate release notes
        uses: ./.github/actions/generate-guidewire-releasenotes
        with:
          OUTPUT_FILE: release-notes/trunk-release-notes.json
          RELEASE_VERSION: v$(cat ./version.json | jq -r '.version')
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Uploading application and infrastructure artifacts to Github Releases
        if: startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'hotfix')
        uses: ./.github/actions/create-update-release
        with:
          # Added a 'v' to the tag name to follow agreed standards for release versioning (e.g. v1.0.0)
          name: v$(cat ./version.json | jq -r '.version')
          target: ${{ github.ref_name }}
          artifacts: release-notes/${{ github.ref_name }}-release-notes.json
          artifact-name: app-package