name: build

on:
  # push:
  #   branches:
  #     - main
  #     - 'release/**'
  workflow_dispatch:

permissions:
  contents: write  # Need write permission to commit back to repo
  pull-requests: read  # Need to read PR information

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for git log

      ### Trunk build release notes generation ###
      - name: Generate trunk build release notes
        if: startsWith(github.ref_name, 'main')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FILE: release-notes/trunk-release-notes.json
        run: |
          bash .github/scripts/generate-trunk-build-notes.sh

      - name: Commit and push trunk release notes
        if: startsWith(github.ref_name, 'main')
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add release-notes/${{ steps.build-type.outputs.output_file }}

          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update release notes [skip ci]"
            git push
          fi

      ### Release build release notes generation ###
      - name: Generate release build release notes
        if: startsWith(github.ref_name, 'release/**')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: v$(cat ./version.json | jq -r '.version')
        run: |
          bash .github/scripts/generate-release-build-notes.sh

      - name: Uploading application and infrastructure artifacts to Github Releases
        if: startsWith(github.ref_name, 'release') || startsWith(github.ref_name, 'hotfix')
        uses: ./.github/actions/create-update-release
        with:
          # Added a 'v' to the tag name to follow agreed standards for release versioning (e.g. v1.0.0)
          name: v$(cat ./version.json | jq -r '.version')
          target: ${{ github.ref_name }}
          artifacts: release-notes/${{ github.ref_name }}-release-notes.json
          artifact-name: app-package